### ISSUE TITLE
dp2ppgen doesn't seem to handle *-- at the top of a page

### ISSUE THREAD

**Issue by wf49670** [davem2/dp2ppgen#3]
This one is perhaps hard to recognize, given everything that's going on. But running with -pcfjse 
--fndest=chapterend and this input:

> states--the island of Cyprus and the kingdom of Cappadocia[2]
> 
> [Footnote 1: A vacancy was made in the college of augurs in <sc>B.C.</sc> 59 by the death
> of Metellus Celer, which Cicero would have liked to fill (see vol. i.,
> p. 90). But he was not nominated as one of the two candidates, as was
> necessary. He filled the vacancy caused by the death of P. Crassus <sc>B.C.</sc> 53.]
> 
> [Footnote 2: Cato, to get him out of Rome, had been sent in <sc>B.C.</sc> 58 on the
> motion of Clodius to take over Cyprus; he therefore (as usual) became
> its patron. It is not known why he was specially connected with
> Cappadocia and Deiotarus, but client kings generally selected some]*
> -----File: 123.png---\Meghan\tenaj\monsourster\grumbuskin----------------
> //[Sidenote: <sc>B.C.</sc> 50, <sc>ÆT.</sc> 56]
> *--have something to say to you about me also. So, too, I
> think, will Deiotarus, who is attached to you with special

I get this output:

> states--the island of Cyprus and the kingdom of Cappadocia[205]
> .bn 123.png // -----------------------( 123.png )-----------------------
> .pn +1
> //[Sidenote: <sc>B.C.</sc> 50, <sc>ÆT.</sc> 56]
> *--have something to say to you about me also. So, too, I
> think, will Deiotarus, who is attached to you with special

The *-- has not been rejoined, and the output messages do not contain any relevant info or error messages to alert the user to necessary manual action. [Edit: using 0.2.0]

**Comment by davem2** [comment]
Thanks for letting me know, I'll add handling for cases like this to spanned formatting joins.

**Comment by davem2** [comment]
Handling for end/start of line emdash/long dash added in 0bb6172811.

The new output should look like:

> states--the island of Cyprus and the kingdom of Cappadocia[205]*--have 
> .bn 123.png // -----------------------( 123.png )-----------------------
> .pn +1
> //[Sidenote: B.C. 50, ÆT. 56]
> something to say to you about me also. So, too, I
> think, will Deiotarus, who is attached to you with special

I left the \* in after the join, though I think it might be more appropriate to strip out for the unclothed dashes/long dash cases.

There is still an outstanding issue where multiline Footnotes, Illustrations or Sidenotes (any [] style markup) between the two joined sections will cause problems. So, in your case above you don't see the issue because the -f option was given as well so the footnotes were relocated on a earlier pass. If you ran with just the -j option, the join would have issues.
